AWSTemplateFormatVersion: 2010-09-09
Description: >-
  AWS CloudFormation Template Create IAM_Users_Groups_and_Policies: This 
  template creates a new IAM user to allow access via the command line
Resources:
  AmplifyUser:
    Type: 'AWS::IAM::User'
  CFNAdminGroup:
    Type: 'AWS::IAM::Group'
  Admins:
    Type: 'AWS::IAM::UserToGroupAddition'
    Properties:
      GroupName: !Ref CFNAdminGroup
      Users:
        - !Ref AmplifyUser
  CFNAdminPolicies:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: AmplifyAdmins
      PolicyDocument:
        Statement:
          - Sid: CLICloudformationPolicy
            Effect: Allow
            Action:
              - 'cloudformation:CreateChangeSet'
              - 'cloudformation:CreateStack'
              - 'cloudformation:DeleteStack'
              - 'cloudformation:DescribeChangeSet'
              - 'cloudformation:DescribeStackEvents'
              - 'cloudformation:DescribeStackResource'
              - 'cloudformation:DescribeStackResources'
              - 'cloudformation:DescribeStacks'
              - 'cloudformation:ExecuteChangeSet'
              - 'cloudformation:GetTemplate'
              - 'cloudformation:UpdateStack'
              - 'cloudformation:ListStackResources'
              - 'cloudformation:DeleteStackSet'
              - 'cloudformation:DescribeStackSet'
              - 'cloudformation:UpdateStackSet'
            Resource:
              - 'arn:aws:cloudformation:*:*:stack/amplify-*'
          - Sid: CLIManageviaCFNPolicy
            Effect: Allow
            Action:
              - 'iam:*'
              - 'appsync:*'
              - 'apigateway:DELETE'
              - 'apigateway:GET'
              - 'apigateway:PATCH'
              - 'apigateway:POST'
              - 'apigateway:PUT'
              - 'cognito-idp:*'
              - 'cognito-identity:*'
              - 'lambda:*'
              - 'dynamodb:*'
              - 's3:*'
              - 'cloudfront:*'
              - 'events:*'
              - 'mobiletargeting:GetApp'
              - 'kinesis:*'
              - 'es:AddTags'
              - 'es:CreateElasticsearchDomain'
              - 'es:DeleteElasticsearchDomain'
              - 'es:DescribeElasticsearchDomain'
              - 's3:PutEncryptionConfiguration'
            Resource: '*'
            Condition:
              'ForAnyValue:StringEquals':
                'aws:CalledVia':
                  - cloudformation.amazonaws.com
          - Sid: CLISDKCalls
            Effect: Allow
            Action:
              - 'appsync:GetIntrospectionSchema'
              - 'appsync:GraphQL'
              - 'appsync:UpdateApiKey'
              - 'appsync:ListApiKeys'
              - 'amplify:*'
              - 'amplifybackend:*'
              - 'amplifyuibuilder:*'
              - 'sts:AssumeRole'
              - 'mobiletargeting:*'
              - 'cognito-idp:*'
              - 'cognito-identity:*'
              - 'dynamodb:*'
              - 'lambda:*'
              - 'iam:*'
              - 'cloudformation:ListStacks'
              - 'sns:CreateSMSSandboxPhoneNumber'
              - 'sns:GetSMSSandboxAccountStatus'
              - 'sns:VerifySMSSandboxPhoneNumber'
              - 'sns:DeleteSMSSandboxPhoneNumber'
              - 'sns:ListSMSSandboxPhoneNumbers'
              - 'sns:ListOriginationNumbers'
              - 'rekognition:DescribeCollection'
              - 'logs:DescribeLogStreams'
              - 'logs:GetLogEvents'
              - 'lex:GetBot'
              - 'lex:GetBuiltinIntent'
              - 'lex:GetBuiltinIntents'
              - 'lex:GetBuiltinSlotTypes'
              - 'cloudformation:GetTemplateSummary'
              - 'codecommit:GitPull'
            Resource: '*'
          - Sid: AmplifySSMCalls
            Effect: Allow
            Action:
              - 'ssm:PutParameter'
              - 'ssm:DeleteParameter'
              - 'ssm:GetParametersByPath'
              - 'ssm:GetParameters'
              - 'ssm:GetParameter'
              - 'ssm:DeleteParameters'
            Resource: 'arn:aws:ssm:*:*:parameter/amplify/*'
          - Sid: GeoPowerUser
            Effect: Allow
            Action:
              - 'geo:*'
            Resource: '*'
          - Sid: AmplifyStorageSDKCalls
            Effect: Allow
            Action:
              - 's3:*'
            Resource: '*'
          - Sid: AmplifySSRCalls
            Effect: Allow
            Action:
              - 'cloudfront:CreateCloudFrontOriginAccessIdentity'
              - 'cloudfront:CreateDistribution'
              - 'cloudfront:CreateInvalidation'
              - 'cloudfront:GetDistribution'
              - 'cloudfront:GetDistributionConfig'
              - 'cloudfront:ListCloudFrontOriginAccessIdentities'
              - 'cloudfront:ListDistributions'
              - 'cloudfront:ListDistributionsByLambdaFunction'
              - 'cloudfront:ListDistributionsByWebACLId'
              - 'cloudfront:ListFieldLevelEncryptionConfigs'
              - 'cloudfront:ListFieldLevelEncryptionProfiles'
              - 'cloudfront:ListInvalidations'
              - 'cloudfront:ListPublicKeys'
              - 'cloudfront:ListStreamingDistributions'
              - 'cloudfront:UpdateDistribution'
              - 'cloudfront:TagResource'
              - 'cloudfront:UntagResource'
              - 'cloudfront:ListTagsForResource'
              - 'iam:AttachRolePolicy'
              - 'iam:CreateRole'
              - 'iam:CreateServiceLinkedRole'
              - 'iam:GetRole'
              - 'iam:PutRolePolicy'
              - 'iam:PassRole'
              - 'lambda:CreateFunction'
              - 'lambda:EnableReplication'
              - 'lambda:DeleteFunction'
              - 'lambda:GetFunction'
              - 'lambda:GetFunctionConfiguration'
              - 'lambda:PublishVersion'
              - 'lambda:UpdateFunctionCode'
              - 'lambda:UpdateFunctionConfiguration'
              - 'lambda:ListTags'
              - 'lambda:TagResource'
              - 'lambda:UntagResource'
              - 'route53:ChangeResourceRecordSets'
              - 'route53:ListHostedZonesByName'
              - 'route53:ListResourceRecordSets'
              - 's3:CreateBucket'
              - 's3:GetAccelerateConfiguration'
              - 's3:GetObject'
              - 's3:ListBucket'
              - 's3:PutAccelerateConfiguration'
              - 's3:PutBucketPolicy'
              - 's3:PutObject'
              - 's3:PutBucketTagging'
              - 's3:GetBucketTagging'
              - 'lambda:ListEventSourceMappings'
              - 'lambda:CreateEventSourceMapping'
              - 'iam:UpdateAssumeRolePolicy'
              - 'iam:DeleteRolePolicy'
              - 'sqs:CreateQueue'
              - 'sqs:DeleteQueue'
              - 'sqs:GetQueueAttributes'
              - 'sqs:SetQueueAttributes'
              - 'amplify:GetApp'
              - 'amplify:GetBranch'
              - 'amplify:UpdateApp'
              - 'amplify:UpdateBranch'
            Resource: '*'
      Groups:
        - !Ref CFNAdminGroup
  CFNKeys:
    Type: 'AWS::IAM::AccessKey'
    Properties:
      UserName: !Ref AmplifyUser
Outputs:
  AccessKey:
    Value: !Ref CFNKeys
    Description: AWSAccessKeyId of new user
  SecretKey:
    Value: !GetAtt 
      - CFNKeys
      - SecretAccessKey
    Description: AWSSecretKey of new user
